"""make winner and score non-nullable

Revision ID: 3040d39cf932
Revises: 7d32fdca7791
Create Date: 2025-10-02 22:39:08.480606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3040d39cf932'
down_revision: Union[str, Sequence[str], None] = '7d32fdca7791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Matches', 'Winner',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Matches', 'Score',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Matches', 'Score',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Matches', 'Winner',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
