"""Initial migration

Revision ID: 7d32fdca7791
Revises:
Create Date: 2025-08-21 23:26:13.845874

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7d32fdca7791'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Players',
        sa.Column('ID', sa.Integer(), nullable=False),
        sa.Column('Name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('ID'),
        sa.UniqueConstraint('Name'),
    )
    op.create_table(
        'Matches',
        sa.Column('ID', sa.Integer(), nullable=False),
        sa.Column('UUID', sa.UUID(), nullable=False),
        sa.Column('Player1', sa.Integer(), nullable=False),
        sa.Column('Player2', sa.Integer(), nullable=False),
        sa.Column('Winner', sa.Integer(), nullable=True),
        sa.Column('Score', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['Player1'],
            ['Players.ID'],
        ),
        sa.ForeignKeyConstraint(
            ['Player2'],
            ['Players.ID'],
        ),
        sa.ForeignKeyConstraint(
            ['Winner'],
            ['Players.ID'],
        ),
        sa.PrimaryKeyConstraint('ID'),
        sa.UniqueConstraint('UUID'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Matches')
    op.drop_table('Players')
    # ### end Alembic commands ###
